### ISSUE TITLE
Transparent background looks bad in some clients

### ISSUE THREAD

**Issue by fitnr** [Objelisks/lsystembot#1]
In Tweetdeck, transparent images are respected, which makes LSystemBot illegible:

![screen shot 2015-04-16 at 1 23 44 pm](https://cloud.githubusercontent.com/assets/714125/7187023/d7e6e88e-e43b-11e4-8b2b-7ba65439d72f.png)

**Comment by cemerick** [comment]
Same in the android official twitter client app, if you tap on the image itself (the in-tweet preview looks good).
